/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/sign_in'
import { Route as HomeImport } from './routes/home'
import { Route as ProfileIdImport } from './routes/profile/$id'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/sign_in',
  path: '/sign_in',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdRoute = ProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/sign_in': {
      id: '/sign_in'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/sign_in': typeof SigninRoute
  '/profile/$id': typeof ProfileIdRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/sign_in': typeof SigninRoute
  '/profile/$id': typeof ProfileIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home': typeof HomeRoute
  '/sign_in': typeof SigninRoute
  '/profile/$id': typeof ProfileIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/sign_in' | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/sign_in' | '/profile/$id'
  id: '__root__' | '/home' | '/sign_in' | '/profile/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  SigninRoute: typeof SigninRoute
  ProfileIdRoute: typeof ProfileIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  SigninRoute: SigninRoute,
  ProfileIdRoute: ProfileIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home",
        "/sign_in",
        "/profile/$id"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/sign_in": {
      "filePath": "sign_in.tsx"
    },
    "/profile/$id": {
      "filePath": "profile/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
